### ISSUE TITLE
loadMore event does not fire

### ISSUE THREAD

**Issue by tyteen4a03** [expandtheroom/jquery-infinite-scroll-helper#16]
I have a test page here: https://snaptee-test-2.myshopify.com/collections/kids?page=1

The initial loading fires fine but when I scroll to the bottom nothing happens.

**Comment by rogden** [comment]
It appears there is a bug with retrieving the correct window scroll top/scrollY value when overflow-x is set to hidden on the html or body tag. Without this value being reported correctly, the calculation used to call the loadMore callback will almost always fail. You can fix it by removing overflow-x: hidden from your html tag.

**Comment by rogden** [comment]
Correction:

The combination of overflow-x: hidden and height: 100% on html/body tag will cause the scrollY value to always be 0. You can remove **either** height: 100% or overflow-x: hidden to make it work correctly.

**Comment by komatzu** [comment]
@rogden I have the same problem: the initial loading fires but when I scroll the div I attached the infiniteScrollHelper to the bottom nothing happens. What are the (css) requirements for the div for the infiniteScrollHelper to work?

**Comment by rogden** [comment]
@komatzu Is the div set to overflow-y: scroll or is it the window that is scrolling? Can you link me to the example? You might also be running into the same issue I responded to above.

**Comment by rogden** [comment]
I pushed up a fix (1.2.2) that addresses an issue with position fixed scroll elements not triggering loadMore callback. Perhaps this will fix your issue.
