### ISSUE TITLE
Triggering on scroll at any window position

### ISSUE THREAD

**Issue by mralessio** [expandtheroom/jquery-infinite-scroll-helper#18]
Hi! 
I instantiate the plugin for the container without overflow-y, which is at the bottom of the content. 
So in my case the scroll container is $(window). triggerInitialLoad: true.
It seems that while scrolling the scroll position is calculated not correct, as loadMore triggers at any position each time after the content was loaded, no matter scrolling up or down.

..and I was just looking for some similar to your plugin helper. Lightweight, clean and not overweighed. As I say you had plans to add 'resume' and 'pause'. It would be really good if you still maintain this project.

Thanks.

**Comment by rogden** [comment]
Can you provide me a link to an example of this so I can investigate?

**Comment by mralessio** [comment]
Tested once again after using the last version. Everything works fine now. Probably the last version has solved this or maybe some bugs were on my side.
Thank you.
