### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by garygreen** [expandtheroom/jquery-infinite-scroll-helper#22]
It would be nice if the dependency on jQuery was removed. There's not really anything too complicated going on in the library so should be relatively easy to remove the dependency.

I personally have stopped using jQuery in my projects (too hefty). Most browsers don't have too many nuances these days (except maybe IE) but where there are, there's plenty of lightweight polyfills available to bridge the gap.

**Comment by rogden** [comment]
@garygreen I agree and I'd like to get around to this in the future.
