### ISSUE TITLE
Add one_page_more method

### ISSUE THREAD

**Issue by Alplob** [expandtheroom/jquery-infinite-scroll-helper#24]
Hello,

I am trying to add a new method in order to load the following page programmatically (I need this method because I use the infinite scroll along with a control to filter loaded results - if no result I would like to let the end user loads more data). I added the code below and it loads one more page successfully when I call it. However, this method seems to break the plugin as the infinite scroll does not work anymore after that. Is it possible to load the following page programmatically without breaking the plugin ? Thanks!

```
Plugin.prototype.one_page_more = function() {
    this._beginLoadMore(0);
};
```

**Comment by pierresh** [comment]
Hello,

Actually, after having testing more, it works well when I use the function _done()_ in _loadMore: function(page, done) { }_  instead of _doneLoading: function() { }_.
